# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db25d74bcc3f583c6046ea42eaad3c93cd29e219624badd3e7186de1fe44c7d85a37ba0a41ebd42713fc7c1608570e80305c43523b2b623502c8481ebad5ada3

test:
  secret_key_base: 7caaa47f48e837034090243341f1ca72b0a65faa45f175c7084b7b4c6893bbfa3af4b0a2cf5c2d830f6b0960839fbb5a5ac539f9956ae143b909f65dca2cbeef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
